Support for hack files on VM delete. Briefly tested.

diff --git a/fast-vm b/fast-vm
--- a/fast-vm
+++ b/fast-vm
@@ -148,7 +148,7 @@ usage () {
 	echo ''
 	case $part in
 		import_image)
-			echo "$0 import_image ImageName <empty |PathToImage> PathToLibvirtXML [PathToHacksFile]"
+			echo "$0 import_image ImageName <empty |PathToImage> PathToLibvirtXML [PathToHacksFile] [PathToDeleteHackFile]"
 			;;
 		export_image)
 			echo "$0 export_image ImageName <xz|gz>"
@@ -175,7 +175,7 @@ usage () {
 			echo "$0 ssh VmNumber [/path/to/custom/script]"
 			;;
 		delete)
-			echo "$0 delete VmNumber"
+			echo "$0 delete VmNumber [PathToDeleteHackFile]"
 			;;
 		edit_note)
 			echo "$0 edit_note VmNumber [NoteText]"
@@ -190,12 +190,12 @@ usage () {
 cat <<EOF
 fast-vm <action> <options>
 
-fast-vm import_image ImageName <empty |PathToImage> PathToLibvirtXML [PathToHacksFile]
+fast-vm import_image ImageName <empty |PathToImage> PathToLibvirtXML [PathToHacksFile] [PathToDeleteHackFile]
 fast-vm export_image ImageName <xz|gz>
 fast-vm remove_image ImageName
 fast-vm list_images [short]
 fast-vm create ImageName <base |VmNumber> [PathToLibvirtXML] [PathToHacksFile]
-fast-vm delete VmNumber
+fast-vm delete VmNumber [PathToDeleteHackFile]
 fast-vm edit_note VmNumber [NoteText]
 fast-vm info VmNumber
 fast-vm list [all|active|inactive [short]]
@@ -327,6 +327,15 @@ case "$1" in
 				hack_file=$(download_file "$hack_file")
 			fi
 		fi
+		delete_hack_file="$6"
+		if [ ! -z "$delete_hack_file" ]; then
+			check_file "$delete_hack_file" "delete hack file"
+			if [ "$?" = 2 ]; then pmsg $P_ERROR "delete hack file $delete_hack_file not found\n"; exit 2; fi
+			if [ "$file_local" = '0' ]; then
+				delete_hack_file=$(download_file "$delete_hack_file")
+			fi
+		fi
+
 		if [ -b "/dev/$THINPOOL_VG/$VM_PREFIX$image_name" ]; then
 			pmsg $P_ERROR "base image for '$image_name' version already exists. To remove image use 'remove_image' parameter\n"
 			exit 1
@@ -398,6 +407,15 @@ case "$1" in
 			else
 				cp "$hack_file" "$FASTVM_USER_CONF_DIR/hacks-${image_name}.sh" 2>&1|$DEBUG_LOG_CMD
 				chmod +rx "$FASTVM_USER_CONF_DIR/hacks-${image_name}.sh" 2>&1|$DEBUG_LOG_CMD
+			fi
+		fi
+		if [ ! -z "$delete_hack_file" ] && [ -f "$delete_hack_file" ]; then
+			if [ $(whoami) = 'root' ]; then
+				cp "$delete_hack_file" "$FASTVM_SYSTEM_CONF_DIR/delete-hacks-${image_name}.sh" 2>&1|$DEBUG_LOG_CMD
+				chmod +rx "$FASTVM_SYSTEM_CONF_DIR/delete-hacks-${image_name}.sh" 2>&1|$DEBUG_LOG_CMD
+			else
+				cp "$delete_hack_file" "$FASTVM_USER_CONF_DIR/delete-hacks-${image_name}.sh" 2>&1|$DEBUG_LOG_CMD
+				chmod +rx "$FASTVM_USER_CONF_DIR/delete-hacks-${image_name}.sh" 2>&1|$DEBUG_LOG_CMD
 			fi
 		fi
 
@@ -477,10 +495,12 @@ case "$1" in
 			pmsg $P_DEBUG "removing XML and hack file of $image_name...\n"
 			if [ -f "$FASTVM_USER_CONF_DIR/config-${image_name}.xml" ]; then rm "$FASTVM_USER_CONF_DIR/config-${image_name}.xml"; fi
 			if [ -f "$FASTVM_USER_CONF_DIR/hacks-${image_name}.sh" ]; then rm "$FASTVM_USER_CONF_DIR/hacks-${image_name}.sh"; fi
+			if [ -f "$FASTVM_USER_CONF_DIR/delete-hacks-${image_name}.sh" ]; then rm "$FASTVM_USER_CONF_DIR/delete-hacks-${image_name}.sh"; fi
 			if [ $(whoami) = 'root' ]; then
 				pmsg $P_DEBUG "removing system-wide XML and hack file ...\n"
 				if [ -f "$FASTVM_SYSTEM_CONF_DIR/config-${image_name}.xml" ]; then rm "$FASTVM_SYSTEM_CONF_DIR/config-${image_name}.xml"; fi
 				if [ -f "$FASTVM_SYSTEM_CONF_DIR/hacks-${image_name}.sh" ]; then rm "$FASTVM_SYSTEM_CONF_DIR/hacks-${image_name}.sh"; fi
+				if [ -f "$FASTVM_SYSTEM_CONF_DIR/delete-hacks-${image_name}.sh" ]; then rm "$FASTVM_SYSTEM_CONF_DIR/delete-hacks-${image_name}.sh"; fi
 			fi
 			pmsg $P_INFO "image $image_name removed\n"
 		else
@@ -743,6 +763,24 @@ case "$1" in
 			exit 1
 		fi
 
+		# determine image name of VM
+		image_name=$(virsh --connect qemu:///system list --all|awk '{print $2,$3,$4}'|egrep "^${VM_PREFIX}.*-[0-9]+ "|sed "s/${VM_PREFIX}\(.\+\)-\([0-9]\+\) \(.\+\)$/\2 \1 \3/"|awk "\$1==$vm_number {printf \"%s\",\$2}")
+
+		delete_hack_file=""
+		for path in "$3" "$FASTVM_USER_CONF_DIR/delete-hacks-${image_name}.sh" "$FASTVM_SYSTEM_CONF_DIR/delete-hacks-${image_name}.sh"
+		do
+			check_file "$path" "delete hack file at $path" 2>&1 >/dev/null
+			if [ "$?" != 2 ]; then
+				if [ "$file_local" = '0' ]; then
+		                        delete_hack_file=$(download_file "$path")
+				else
+					delete_hack_file="$path"
+		                fi
+				pmsg $P_DEBUG "using file $path as delete hack file\n"
+				break
+			fi
+		done
+
 		if [ "$FASTVM_OWNER_ONLY_DELETE" == "yes" ]; then
 			owner=$(stat --format="%U" "$FASTVM_NOTES_DIR/$vm_number" 2>/dev/null)
 			if [ $(whoami) != "root" ] && [ $(whoami) != "$owner" ]; then
@@ -785,6 +823,17 @@ case "$1" in
 
 		pmsg $P_DEBUG "removing VM notes\n"
 		if [ -f "$FASTVM_NOTES_DIR/$vm_number" ]; then rm "$FASTVM_NOTES_DIR/$vm_number"; fi
+
+		## apply delete hack file
+		if [ ! -z "$delete_hack_file" ]; then
+			delete_hack_file=$(echo "$delete_hack_file"|sed 's/^\([^\/]\)/\.\/\1/g')
+			pmsg $P_DEBUG "applying delete hacks from $delete_hack_file\n"
+			. $delete_hack_file
+			if [ ! "$?" -eq "0" ]; then
+				pmsg $P_WARNING "there was issue applying delete hacks to this machine, check syslog for more details\n"
+			fi
+			pmsg $P_DEBUG "applying delete hacks finished\n"
+		fi
 
 		pmsg $P_DEBUG "undefining VM $vm_name from libvirt\n"
 		virsh --connect qemu:///system undefine $vm_name --nvram
@@ -864,8 +913,8 @@ case "$1" in
 		if [ ! -z "$short_output" ] && [ "$short_output" = "short" ]; then
 			echo "$image_name_list"
 		else
-				printf '%-20s|%-17s |%-17s |\n' 'Image' 'SYSTEM' 'USER'
-				printf '%-20s|%-8s %-9s|%-8s %-9s|\n' 'Image name' 'XML' 'Hack file' 'XML' 'Hack file'
+				printf '%-20s|%-21s |%-21s |\n' 'Image' 'SYSTEM' 'USER'
+				printf '%-20s|%-8s %-13s|%-8s %-13s|\n' 'Image name' 'XML' 'Hack file for' 'XML' 'Hack file for'
 			for image_name in $image_name_list; do
 				# check the existence of the XML file
 				if [ -f "$FASTVM_USER_CONF_DIR/config-${image_name}.xml" ]; then
@@ -874,10 +923,12 @@ case "$1" in
 					user_xml_exists="missing"
 				fi
 				# check existence of hack file
+				user_hacks_exists="no hack files"
 				if [ -f "$FASTVM_USER_CONF_DIR/hacks-${image_name}.sh" ]; then
-					user_hacks_exists="ok"
-				else
-					user_hacks_exists="missing"
+					user_hacks_exists="create"
+				fi
+				if [ -f "$FASTVM_USER_CONF_DIR/delete-hacks-${image_name}.sh" ]; then
+					user_hacks_exists+=",delete"
 				fi
 				# check the existence of the XML file
 				if [ -f "$FASTVM_SYSTEM_CONF_DIR/config-${image_name}.xml" ]; then
@@ -886,15 +937,17 @@ case "$1" in
 					system_xml_exists="missing"
 				fi
 				# check existence of hack file
+				system_hacks_exists="no hack files"
 				if [ -f "$FASTVM_SYSTEM_CONF_DIR/hacks-${image_name}.sh" ]; then
-					system_hacks_exists="ok"
-				else
-					system_hacks_exists="missing"
+					system_hacks_exists="create"
 				fi
-				printf "%-20s %-8s %-9s %-8s %-9s\n" "$image_name" "$system_xml_exists" "$system_hacks_exists" "$user_xml_exists" "$user_hacks_exists"
+				if [ -f "$FASTVM_SYSTEM_CONF_DIR/delete-hacks-${image_name}.sh" ]; then
+					system_hacks_exists=",delete"
+				fi
+				printf "%-20s|%-8s %-13s|%-8s %-13s|\n" "$image_name" "$system_xml_exists" "$system_hacks_exists" "$user_xml_exists" "$user_hacks_exists"
 			done
-			printf "\nNOTE: if image is missing XML it wouldn't be possible to create a VM from it!\n Image with missing hack file can work if it's not needed.\n"
-			printf "\n USER XML and hack files takes precendense before SYSTEM ones.\n"
+			printf "\nNOTE: if image is missing XML it wouldn't be possible to create a VM from it!\n Image with missing hack file(s) can work if it's not needed.\n"
+			printf "\n USER XML and hack file(s) takes precendense before SYSTEM ones.\n"
 		fi
 		;;
 	info)
