context-aware help

diff --git a/fast-vm b/fast-vm
--- a/fast-vm
+++ b/fast-vm
@@ -16,23 +16,56 @@ function check_empty {
 }
 
 function usage {
-	echo "usage:"
-	echo "$0 import_image rhel_version /path/to/image.gz /path.to/image/libvirt.xml [/path/to/hack_file.sh]"
-	echo " - import VM image to thin LVM storage and define default libvirt XML and optionaly hacks file"
-	echo "$0 create rhel_version VM_number/base"
-	echo " - creates VM based on image from thin LVM with specified number or 'base VM'"
-	echo "$0 start VM_number [console]"
-	echo " - starts VM with number VM_number, if parameter 'console is passed' it also connects to serial console after start"
-	echo "$0 console VM_number"
-	echo " - connect to serial console of VM with number VM_number"
-	echo "$0 delete VM_number"
-	echo " - delete VM with number VM_number and it's thin LV disk"
+	part="$1"
+
+	echo ''
+	case $part in
+		import_image)
+			echo "fast-vm import_image <rhel_version> <image.gz> <libvirt.xml> [ <hack_file.sh> ]"
+			echo "  <rhel_version> - number for imported rhel version (f.e. 6_7)"
+			echo "  <image.gz> - gziped VM drive to be imported"
+			echo "  <libvirt.xml> - default libvirt VM xml definition for this version"
+			echo "  <hack_file.sh> (optional) - bash script executed after creating VM "
+			echo "                              (f.e. used for change of hostname)"
+			;;
+		create)
+			echo "fast-vm create <rhel_version> <VM_number>/base"
+			echo "  <rhel_version> - version of rhel to use for this VM (new ones can be defined using import_image)"
+			echo "  <VM_number>/base - number of VM which you use to identify the VM, the VM also gets assigned"
+			echo "                   static DHCP lease in form of 192.168.XX.<VM_number>."
+			echo " 		         - alternatively special value 'base' denotas creation of base VM"
+			;;
+		start)
+			echo "fast-vm start <VM_number> [ console ]"
+			echo "  <VM_number> - number of VM to start"
+			echo "  console (optional) - if present you get connected to VMs serial console after starting it"
+			;;
+		console)
+			echo "fast-vm console <VM_number>"
+			echo "  <VM_number> - number of VM to start"
+			;;
+		delete)
+			echo "fast-vm delete <VM_number>"
+			echo "  <VM_number> - number of VM to start"
+			;;
+		*)
+			echo "fast-vm <action> <options>"
+			echo "  <action> :"
+			echo "    import_image - import VM image to thin LVM storage and define default libvirt XML "
+			echo " 	                 and optionaly hacks file"
+			echo "    create - creates VM based on image from thin LVM"
+			echo "    start - starts VM and optionally also connects to serial console after start"
+			echo "    console - connect to serial console of running VM"
+			echo "    delete - delete VM and its thin LV disk drive"
+			echo " for more details run 'fast-vm <action>' without options to see more help"
+			echo "== fast-vm version 0.1 <ofamera@redhat.com> =="
+			;;
+	esac
+	exit 1
 }
 
-if [ -z "$1" ]; then
-	usage
-	exit 1
-fi
+# first parameter is compulsory
+if [ -z "$1" ]; then usage; fi
 
 ## fast-vm configuration
 if [ ! -f "$HOME/.fast-vm/config" ]; then
@@ -53,24 +86,16 @@ check_empty "SUBNET_NUMBER" "$SUBNET_NUMBER"
 case "$1" in
 	import_image)
 		rhel_version="$2"
-		if [ -z "$rhel_version" ]; then
-			echo "[err] missing rhel version"
-			exit 1
-		fi
+		if [ -z "$rhel_version" ]; then echo "[err] missing rhel version"; usage import_image; fi
 		image_path="$3"
-		if [ ! -f "$image_path" ]; then
-			echo "[err] image file not found"
-			exit 1
-		fi
+		if [ ! -f "$image_path" ]; then echo "[err] image file not found"; usage import_image; fi
 		image_xml_path="$4"
-		if [ ! -f "$image_xml_path" ]; then
-			echo "[err] image xml file not found"
-			exit 1
-		fi
+		if [ ! -f "$image_xml_path" ]; then echo "[err] image xml file not found"; usage import_image; fi
+
 		hack_file="$5"
 		if [ ! -z "$hack_file" ] && [ ! -f "$hack_file" ]; then
 			echo "[err] hack file not found"
-			exit 1
+			usage import_image
 		fi
 
 		if [ -b "/dev/$THINPOOL_VG/$VM_PREFIX$rhel_version" ]; then
@@ -78,7 +103,7 @@ case "$1" in
 			echo "[???] Do you want to overwrite it (y/n): "
 			read answer
 			if [ ! "$answer" == "y" ]; then
-				echo "aborting, no changes made"
+				echo "[inf] aborting, no changes made"
 				exit 0
 			fi
 			echo "[inf] overwriting LV $VM_PREFIX$rhel_version ..."
@@ -112,9 +137,8 @@ case "$1" in
 		;;
 	create)
 		rhel_version="$2"
-		if [ -z "$rhel_version" ]; then
-			echo "[err] missing rhel version"
-			exit 1
+		if [ -z "$rhel_version" ]; then echo "[err] missing rhel version"; usage create; fi
+
 		fi
 
 		if [ ! -f "$HOME/.fast-vm/config-${rhel_version}.xml" ]; then
@@ -134,14 +158,14 @@ case "$1" in
 		then
 			if [ "$vm_number" -lt 20 ] || [ "$vm_number" -gt 220 ];then
 				echo "[err] VM number out of range (20-220)"
-				exit 1
+				usage create
 			fi
 		else
 			if [ "$vm_number" == "base" ]; then
 				echo "[inf] creating base image VM"
 			else
 				echo "[err] only numbers from range 20-220 and word 'base' permited here"
-				exit 1
+				usage create
 			fi
 		fi
 
@@ -202,10 +226,7 @@ case "$1" in
 
 	start)
 		vm_number="$2"
-		if [ -z "$vm_number" ]; then 
-			echo "[err] VM number missing"
-			exit 1
-		fi
+		if [ -z "$vm_number" ]; then echo "[err] VM number missing"; usage start; fi
 		
 		vm_name=$(virsh list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")
 
@@ -225,10 +246,8 @@ case "$1" in
 		;;
 	console)
 		vm_number="$2"
-		if [ -z "$vm_number" ]; then 
-			echo "[err] VM number missing"
-			exit 1
-		fi	
+		if [ -z "$vm_number" ]; then echo "[err] VM number missing"; usage console; fi
+
 		vm_name=$(virsh list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")
 		if [ -z "$vm_name" ]; then
 			echo "[err] VM with number '$vm_number' not found"
@@ -239,10 +258,8 @@ case "$1" in
 		;;
 	delete)
 		vm_number="$2"
-		if [ -z "$vm_number" ]; then 
-			echo "[err] VM number missing"
-			exit 1
-		fi	
+		if [ -z "$vm_number" ]; then echo "[err] VM number missing"; usage delete; fi
+
 		vm_name=$(virsh list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")
 		if [ -z "$vm_name" ]; then
 			echo "[err] VM with number '$vm_number' not found"
